### ISSUE TITLE
GPIO RPi CM4

### ISSUE THREAD

**Issue by Magdalena22** [antmicro-labs/open-source-video-previewer#5]
What should we plan to do with rpi's gpio pins, which aren't present in Jetson Nano

**Comment by kgugala** [comment]
if there is room you may route them to some kind of pinheader. You can also add a few user LEDs.

How many GPIOs are we talking about?

**Comment by MateuszGora** [comment]
Standard GPIO user connector. 28 GPIO’s + 12 dedicated for power supply

**Comment by tgorochowik** [comment]
I think it makes sense to keep a RPi compatible header if you don't need the pins elsewhere.

So the priorities would be:
* Make sure you have all the external connections use dedicated ports (e.g. when routing UART prefer to place an ftdi chip on the board and use a dedicated USB port instead of requiring the usage of external UART adapters, don't route the Ethernet pins to the gold pin headers, use a dedicated Ethernet port etc.)
* Route any remaining but potentially useful connectors to a standard goldpin header - if it is possible to keep the order of the pins compatible with RPi shields - please do so
* It is okay if you decide not to use all signals - just make sure it is okay if they are floating - if not, make sure to use the required measures to stop them from producing any interference (e.g. pull down resistors)

It is also okay to change the form factor of the board to accommodate the additional connectors, but try to keep the board compact nonetheless.
