### ISSUE TITLE
External voltage source: 5 or 12 V?

### ISSUE THREAD

**Issue by Magdalena22** [antmicro-labs/open-source-video-previewer#8]

**Comment by pkatarzynski** [comment]
Do you mean power supply voltage for the board or literally external power supply delivered by the board?

**Comment by MateuszGora** [comment]
We asked what kinds of power supply shall be delivery to the board, but problem was solved because, PCIe need power supply 12V and 3.3V.

In this case we have three supply voltage:
(1) Main: 12V -> PCIe  
(2) 12v -> 5V @ 3A by buck converter
(3) 12v -> 3.3V @ 3A  by buck converter (for PCIe - Only)

(*) 3.3V (600mA) comming  direct from chip ARM for user GPIO
